<?php

namespace App\Services\Admin;

use App\Models\SeoPerformanceStat;
use App\Models\AiDiagnose;
use App\Models\SentinelAudit;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;

class AdminReportService
{
    /**
     * UNICORP-GRADE: Comprehensive Daily Heartbeat (08:00 WIB)
     */
    public function generateDailySummary()
    {
        Log::info("[SENTINEL-REPORT] Compiling daily summary...");

        $stats = $this->getSeoPerformance();
        $aiUsage = $this->getAiMetrics();
        $health = $this->getSystemHealth();

        $message = "*RooterIN Daily Report* (" . date('d M Y') . ")\n\n";

        // 1. SEO Insights
        $message .= "*SEO Performa:*\n";
        if ($stats && count($stats) > 0) {
            foreach (array_slice($stats->toArray(), 0, 3) as $stat_data) {
                $stat = (object)$stat_data;
                $message .= "- {$stat->query}: {$stat->clicks} Kliks / {$stat->impressions} Impresi\n";
            }
        } else {
            $message .= "- Data performa belum tersedia.\n";
        }

        // 2. AI Intelligence Stats
        $message .= "\n*AI Intel:*\n";
        $message .= "- Total Diagnosis: " . $aiUsage['total_today'] . " sesi\n";
        $message .= "- Sisa Kuota API: " . $aiUsage['quota_left'] . "%\n";

        // 3. System Resilience (Sentinel)
        $message .= "\n*System Health:*\n";
        $message .= "- Node Status: " . $health['status'] . "\n";
        $message .= "- Latency: " . $health['latency'] . "ms\n";
        $message .= "- Backup: " . $health['last_backup'] . "\n";

        $message .= "\n_Generated by Sentinel V1.2 (Unicorp)_";

        // Deliver via WhatsApp
        app(\App\Services\Sentinel\SentinelService::class)->sendWhatsAppAlert($message);

        return $message;
    }

    protected function getSeoPerformance()
    {
        return SeoPerformanceStat::where('date', date('Y-m-d', strtotime('-2 days')))
            ->orderBy('clicks', 'desc')
            ->get();
    }

    protected function getAiMetrics()
    {
        $today = date('Y-m-d');
        $total = AiDiagnose::whereDate('created_at', $today)->count();
        $guard = app(\App\Services\Ai\AiQuotaGuardService::class);
        $health = $guard->getHealth();

        return [
            'total_today' => $total,
            'quota_left' => ($health['total_nodes'] > 0) ? (1 - ($health['active_index'] / $health['total_nodes'])) * 100 : 0
        ];
    }

    protected function getSystemHealth()
    {
        $lastAudit = SentinelAudit::orderBy('id', 'desc')->first();
        $metrics = $lastAudit ? $lastAudit->metrics : null;

        return [
            'status' => Cache::get('security_pulse_status', 'IRON-CLAD'),
            'latency' => $metrics['db_latency'] ?? 'Unknown',
            'last_backup' => Cache::get('last_successful_backup') ? \Carbon\Carbon::parse(Cache::get('last_successful_backup'))->diffForHumans() : 'FAIL'
        ];
    }
}
